const { chromium } = require(process.env.PLAYWRIGHT_PATH || 'playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
(async () => {
  const browser = await chromium.launch({ headless: true, channel: process.env.BROWSER_CHANNEL || 'msedge' });
  const context = await browser.newContext({ viewport: { width: 1440, height: 1100 } });
  const page = await context.newPage();
  const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  await page.goto('http://127.0.0.1:4173');
  const legacy = { version: '1.5.0', startDate: '2026-05-01', operatedSide: 'Left', logs: { 'w1-d1-evening': { complete: true, exercises: { 'd1e-pushup': { done: true, sets: ['8', '9', '10'], load: 'bench' } }, notes: 'original history', updatedAt: '2026-05-01T12:00:00Z' } }, goals: { pullups: '3', checklist: {} } };
  await page.evaluate(data => localStorage.setItem('moveStrongRehabStateV1', JSON.stringify(data)), legacy);
  await page.reload();
  await page.getByRole('heading', { name: 'Make space for feeling stronger.' }).waitFor();
  await page.locator('[data-routine="water"]').click();
  await page.reload();
  assert.equal(await page.locator('[data-routine="water"]').getAttribute('aria-pressed'), 'true');
  assert.deepEqual(await page.evaluate(() => JSON.parse(localStorage.getItem('moveStrongRehabStateV1')).logs), legacy.logs);
  assert.deepEqual(await page.evaluate(() => JSON.parse(localStorage.getItem('moveStrongRehabPreHealthOSV1'))), legacy);
  fs.mkdirSync(path.join(__dirname, '..', 'artifacts'), { recursive: true });
  await page.screenshot({ path: 'artifacts/today-desktop.png', fullPage: true });
  await page.locator('[data-route="plan"]').click();
  assert.equal(await page.locator('.os-calendar-day').count(), 7);
  await page.locator('[data-os="month"]').click();
  assert.equal(await page.locator('.os-calendar-day').count(), 42);
  await page.locator('[data-route="train"]').click();
  await page.locator('#os-date').fill('2026-09-14');
  await page.locator('#os-date').dispatchEvent('change');
  await page.locator('[data-os="session"]').click();
  await page.locator('[data-set-index]').first().fill('8');
  await page.locator('[data-set-index]').first().dispatchEvent('change');
  await page.locator('[data-guide-exercise]').first().click();
  await page.locator('#exerciseOverlay:not(.hidden)').waitFor();
  await page.locator('#guideClose').click();
  await page.locator('#os-minutes').fill('45');
  await page.getByRole('button', { name: 'Finish session ✓', exact: true }).click();
  await page.getByRole('button', { name: 'Reopen session', exact: true }).waitFor();
  await page.locator('[data-route="home"]').click();
  await page.locator('[data-os="recovery"]').first().click();
  await page.locator('#os-sleep').fill('7.5');
  await page.locator('#os-shoulder').fill('3');
  await page.locator('#os-energy').selectOption('steady');
  await page.getByRole('button', { name: 'Save check-in', exact: true }).click();
  await page.getByText('Reduce shoulder loading today.', { exact: false }).first().waitFor();
  await page.locator('#sauna-form #os-minutes').fill('10');
  await page.locator('#sauna-form #os-saunaSkin').selectOption('fine');
  await page.getByRole('button', { name: 'Log sauna session', exact: true }).click();
  await page.locator('[data-route="progress"]').click();
  await page.locator('#os-best-pull').fill('3 strict reps');
  await page.locator('[data-track="pull"] button').click();
  await page.locator('[data-route="settings"]').click();
  await page.locator('#os-workout').fill('07:15');
  await page.getByRole('button', { name: 'Save preferences', exact: true }).click();
  await page.reload();
  await page.locator('[data-route="settings"]').click();
  assert.equal(await page.locator('#os-workout').inputValue(), '07:15');
  await page.locator('[data-os="test-reminder"]').click();
  await page.locator('[data-choice="snooze"]').click();
  assert.equal(await page.locator('.os-reminder').count(), 0);
  const downloadEvent = page.waitForEvent('download');
  await page.locator('[data-os="export-calendar"]').click();
  const download = await downloadEvent;
  assert.match(fs.readFileSync(await download.path(), 'utf8'), /BEGIN:VALARM/);
  const before = await page.evaluate(() => JSON.parse(localStorage.getItem('moveStrongRehabStateV1')));
  await page.locator('#importInput').setInputFiles({ name: 'backup.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify({ state: { ...legacy, logs: { ...legacy.logs, 'w2-d1-home': { complete: true, exercises: {}, notes: 'imported' } } } })) });
  await page.waitForFunction(() => JSON.parse(localStorage.getItem('moveStrongRehabStateV1')).logs['w2-d1-home']);
  const after = await page.evaluate(() => JSON.parse(localStorage.getItem('moveStrongRehabStateV1')));
  assert.deepEqual(after.healthOS, before.healthOS);
  assert.deepEqual(after.logs['w1-d1-evening'], legacy.logs['w1-d1-evening']);
  await page.locator('[data-os="archive"]').click();
  assert.ok(await page.locator('[data-plan-open]').count());
  await page.locator('[data-plan-open]').first().click();
  await page.locator('#completeSessionBtn').waitFor();
  await page.locator('#backBtn').click();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: 'artifacts/today-mobile.png', fullPage: true });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  await page.locator('[data-route="plan"]').click();
  await page.screenshot({ path: 'artifacts/calendar-mobile.png', fullPage: true });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  await page.evaluate(() => Promise.race([navigator.serviceWorker.ready, new Promise((_, reject) => setTimeout(() => reject(new Error('Service worker did not activate')), 10000))]));
  await page.reload();
  await context.setOffline(true);
  await page.reload();
  await page.getByRole('heading', { name: 'Make space for feeling stronger.' }).waitFor();
  assert.equal(errors.length, 0, errors.join('\n'));
  await context.setOffline(false);
  await page.evaluate(() => localStorage.setItem('moveStrongRehabStateV1', '{broken'));
  await page.reload();
  await page.getByText('Your saved data needs attention').waitFor();
  assert.equal(await page.evaluate(() => localStorage.getItem('moveStrongRehabStateV1')), '{broken');
  await browser.close();
  console.log('PASS: desktop/mobile, logs, routines, calendars, sessions, recovery, sauna, milestones, settings, reminders, export, import, archive, offline, corrupt-data protection');
})().catch(error => { console.error(error); process.exit(1); });
