const { chromium } = require(process.env.PLAYWRIGHT_PATH || 'playwright');
const assert = require('node:assert/strict');
(async () => {
  const browser = await chromium.launch({ headless: true, channel: 'msedge' });
  try {
    const page = await browser.newPage({ viewport: { width: 390, height: 844 } });
    const errors = [];
    page.on('pageerror', e => errors.push(e.message));
    await page.goto('http://127.0.0.1:4173');
    await page.locator('[data-route="plan"]').click();
    await page.locator('[data-os="month"]').click();
    await page.locator('[data-os="next-period"]').click();
    const calendar = await page.locator('.os-calendar').innerText();
    await page.locator('[data-date]').nth(12).click();
    await page.goBack();
    await page.locator('.os-calendar.month').waitFor();
    assert.equal(await page.locator('.os-calendar').innerText(), calendar);
    await page.locator('[data-route="train"]').click();
    await page.locator('#os-date').fill('2026-09-21');
    await page.locator('#os-date').dispatchEvent('change');
    await page.locator('[data-os="session"]').click();
    await page.locator('[data-set-index]').first().fill('7');
    await page.locator('[data-set-index]').first().dispatchEvent('change');
    await page.locator('[data-guide-exercise]').first().click();
    await page.goBack();
    await page.locator('#exerciseOverlay.hidden').waitFor({ state: 'attached' });
    assert.equal(await page.locator('[data-set-index]').first().inputValue(), '7');
    await page.locator('#os-minutes').fill('42');
    await page.locator('[data-os="rest"]').click();
    await page.goBack();
    await page.locator('#timerOverlay.hidden').waitFor({ state: 'attached' });
    assert.equal(await page.locator('#os-minutes').inputValue(), '42');
    await page.goBack();
    await page.locator('#os-date').waitFor();
    assert.equal(await page.locator('#os-date').inputValue(), '2026-09-21');
    await page.goForward();
    await page.locator('[data-set-index]').first().waitFor();
    await page.reload();
    assert.equal(await page.locator('[data-set-index]').first().inputValue(), '7');
    await page.locator('[data-route="home"]').click();
    await page.locator('[data-event="light"]').click();
    await page.locator('[data-os="event-complete"]').waitFor();
    await page.goBack();
    await page.locator('.os-agenda').waitFor();
    await page.locator('[data-event="meditation"]').click();
    await page.locator('[data-os="meditate"]').click();
    assert.equal(await page.locator('#timerDisplay').innerText(), '10:00');
    await page.goBack();
    await page.locator('[data-os="event-complete"]').click();
    assert.equal(await page.locator('[data-routine="meditation"]').getAttribute('aria-pressed'), 'true');
    assert.deepEqual(errors, []);
    console.log('PASS: phone Back, calendar context, guides, timer, logs, forward, reload, routine details');
  } finally { await browser.close(); }
})().catch(e => { console.error(e); process.exit(1); });
